package com.restaurant.service.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-05T02:41:22.227+02:00
 * Generated source version: 3.5.5
 *
 */
@WebServiceClient(name = "ServiceService",
                  wsdlLocation = "file:/Users/yc/Documents/WBP/Webservice_Restaurant/com/restaurant/service/src/main/webapp/wsdl/service.wsdl",
                  targetNamespace = "http://www.com.restaurant.service")
public class ServiceService extends javax.xml.ws.Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.com.restaurant.service", "ServiceService");
    public final static QName ServicePort = new QName("http://www.com.restaurant.service", "ServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/yc/Documents/WBP/Webservice_Restaurant/com/restaurant/service/src/main/webapp/wsdl/service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ServiceService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/Users/yc/Documents/WBP/Webservice_Restaurant/com/restaurant/service/src/main/webapp/wsdl/service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort() {
        return super.getPort(ServicePort, Service.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Service
     */
    @WebEndpoint(name = "ServicePort")
    public Service getServicePort(WebServiceFeature... features) {
        return super.getPort(ServicePort, Service.class, features);
    }

}
