
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.restaurant.service.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.5
 * 2023-04-05T02:41:22.212+02:00
 * Generated source version: 3.5.5
 *
 */

@javax.jws.WebService(
                      serviceName = "ServiceService",
                      portName = "ServicePort",
                      targetNamespace = "http://www.com.restaurant.service",
                      wsdlLocation = "file:/Users/yc/Documents/WBP/Webservice_Restaurant/com/restaurant/service/src/main/webapp/wsdl/service.wsdl",
                      endpointInterface = "com.restaurant.service.client.Service")

public class ServicePortImpl implements Service {

    private static final Logger LOG = Logger.getLogger(ServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#getJSONResults(java.lang.String arg0)*
     */
    public com.restaurant.service.client.JsonArray getJSONResults(java.lang.String arg0) {
        LOG.info("Executing operation getJSONResults");
        System.out.println(arg0);
        try {
            com.restaurant.service.client.JsonArray _return = new com.restaurant.service.client.JsonArray();
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#getRestaurantByName(java.lang.String restName)*
     */
    public com.restaurant.service.client.Restaurant getRestaurantByName(java.lang.String restName) {
        LOG.info("Executing operation getRestaurantByName");
        System.out.println(restName);
        try {
            com.restaurant.service.client.Restaurant _return = new com.restaurant.service.client.Restaurant();
            _return.setAddress("Address1302036610");
            _return.setCategory("Category164643118");
            _return.setLat(0.36555897942594195);
            _return.setLon(0.7173661203643945);
            _return.setName("Name2032122100");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#addCategory(java.lang.String cateName)*
     */
    public com.restaurant.service.client.Category addCategory(java.lang.String cateName) {
        LOG.info("Executing operation addCategory");
        System.out.println(cateName);
        try {
            com.restaurant.service.client.Category _return = new com.restaurant.service.client.Category();
            _return.setCateId("CateId-2073912264");
            _return.setCateName("CateName899532901");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#getLonLat(com.restaurant.service.client.Restaurant arg0)*
     */
    public void getLonLat(com.restaurant.service.client.Restaurant arg0) {
        LOG.info("Executing operation getLonLat");
        System.out.println(arg0);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#getRestaurantsByCate(com.restaurant.service.client.Category cate)*
     */
    public java.util.List<com.restaurant.service.client.Restaurant> getRestaurantsByCate(com.restaurant.service.client.Category cate) {
        LOG.info("Executing operation getRestaurantsByCate");
        System.out.println(cate);
        try {
            java.util.List<com.restaurant.service.client.Restaurant> _return = new java.util.ArrayList<com.restaurant.service.client.Restaurant>();
            com.restaurant.service.client.Restaurant _returnVal1 = new com.restaurant.service.client.Restaurant();
            _returnVal1.setAddress("Address1728492342");
            _returnVal1.setCategory("Category-1946489921");
            _returnVal1.setLat(0.24989365433347488);
            _returnVal1.setLon(0.784049060182681);
            _returnVal1.setName("Name1424252624");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.restaurant.service.client.Service#addRestaurant(com.restaurant.service.client.Restaurant restaurant)*
     */
    public java.lang.String addRestaurant(com.restaurant.service.client.Restaurant restaurant) {
        LOG.info("Executing operation addRestaurant");
        System.out.println(restaurant);
        try {
            java.lang.String _return = "_return1554767517";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
