
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "addCategory", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCategory", namespace = "http://www.com.restaurant.service")

public class AddCategory {

    @XmlElement(name = "cateName")
    private java.lang.String cateName;

    public java.lang.String getCateName() {
        return this.cateName;
    }

    public void setCateName(java.lang.String newCateName)  {
        this.cateName = newCateName;
    }

}

