
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "addCategoryResponse", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addCategoryResponse", namespace = "http://www.com.restaurant.service")

public class AddCategoryResponse {

    @XmlElement(name = "return")
    private com.restaurant.model.Category _return;

    public com.restaurant.model.Category getReturn() {
        return this._return;
    }

    public void setReturn(com.restaurant.model.Category new_return)  {
        this._return = new_return;
    }

}

