
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Tue Apr 04 04:15:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "addRestaurant", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addRestaurant", namespace = "http://www.com.restaurant.service")

public class AddRestaurant {

    @XmlElement(name = "restaurant")
    private com.restaurant.model.Restaurant restaurant;

    public com.restaurant.model.Restaurant getRestaurant() {
        return this.restaurant;
    }

    public void setRestaurant(com.restaurant.model.Restaurant newRestaurant)  {
        this.restaurant = newRestaurant;
    }

}

