
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getJSONResultsResponse", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getJSONResultsResponse", namespace = "http://www.com.restaurant.service")

public class GetJSONResultsResponse {

    @XmlElement(name = "return")
    private org.json.JSONArray _return;

    public org.json.JSONArray getReturn() {
        return this._return;
    }

    public void setReturn(org.json.JSONArray new_return)  {
        this._return = new_return;
    }

}

