
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getRestaurantsByCate", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRestaurantsByCate", namespace = "http://www.com.restaurant.service")

public class GetRestaurantsByCate {

    @XmlElement(name = "cate")
    private com.restaurant.model.Category cate;

    public com.restaurant.model.Category getCate() {
        return this.cate;
    }

    public void setCate(com.restaurant.model.Category newCate)  {
        this.cate = newCate;
    }

}

