
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getRestaurantByName", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRestaurantByName", namespace = "http://www.com.restaurant.service")

public class GetRestaurantByName {

    @XmlElement(name = "restName")
    private java.lang.String restName;

    public java.lang.String getRestName() {
        return this.restName;
    }

    public void setRestName(java.lang.String newRestName)  {
        this.restName = newRestName;
    }

}

