
package com.restaurant.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.5.5
 * Wed Apr 05 02:36:44 CEST 2023
 * Generated source version: 3.5.5
 */

@XmlRootElement(name = "getRestaurantsByCateResponse", namespace = "http://www.com.restaurant.service")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getRestaurantsByCateResponse", namespace = "http://www.com.restaurant.service")

public class GetRestaurantsByCateResponse {

    @XmlElement(name = "return")
    private java.util.List<com.restaurant.model.Restaurant> _return;

    public java.util.List<com.restaurant.model.Restaurant> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.restaurant.model.Restaurant> new_return)  {
        this._return = new_return;
    }

}

